version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - message-service
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal

  auth-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

  auth-service:
    build: ./auth-service
    environment:
      DB_CONNECTION: mysql
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_DATABASE: authdb
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      JWT_SECRET: 51acbA7v3m2b81Kbp9mK3HBbhNUswqRHFDyvcAZKtwZ0stWc2QseAI2yFHowXEcJ
    command: >
      sh -c "sleep 10 && php artisan migrate --seed && php-fpm"
    depends_on:
      - redis
      - auth-db
    networks:
      - internal


  message-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: messagedb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

  message-service:
    build: ./message-service
    environment:
      DB_CONNECTION: mysql
      DB_HOST: message-db
      DB_PORT: 3306
      DB_DATABASE: messagedb
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      JWT_SECRET: 51acbA7v3m2b81Kbp9mK3HBbhNUswqRHFDyvcAZKtwZ0stWc2QseAI2yFHowXEcJ
    command: >
      sh -c "sleep 10 && php artisan migrate && php-fpm"
    depends_on:
      - redis
      - auth-db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  auth-db-data:
  message-db-data:
